#%RAML 0.8
title: Steroids Data
mediaType: application/json
baseUri: https://rest-api.appgyver.com/v1

traits:
    - securedBySteroidsApiKey:
        headers:
          steroidsApiKey:
            type: string
            example: exampleapikey
            default: a43a03079eddd336267051830667d0877c7efdb8be30b73daabe841fd23ff0af
          steroidsAppId:
            type: integer
            example: 1234
            default: 113782
  
schemas:
  - Idea_collection: '{"$schema":"http://json-schema.org/schema","title":"Idea collection","type":"object","properties":{"objects":{"type":"array","items":{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical Idea representation","properties":{"title":{"type":"string"},"likes":{"type":"integer"},"shares":{"type":"integer"},"storms":{"type":"integer"},"desc":{"type":"string"},"summary":{"type":"string"},"comments":{"type":"integer"}},"required":[]}}}}'
  - Idea_member: '{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical Idea representation","properties":{"object":{"type":"object","properties":{"title":{"type":"string"},"likes":{"type":"integer"},"shares":{"type":"integer"},"storms":{"type":"integer"},"desc":{"type":"string"},"summary":{"type":"string"},"comments":{"type":"integer"}},"required":[]}}}'
  - Comment_collection: '{"$schema":"http://json-schema.org/schema","title":"Comment collection","type":"object","properties":{"objects":{"type":"array","items":{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical Comment representation","properties":{"text":{"type":"string"},"idea_id":{"type":"string"}},"required":[]}}}}'
  - Comment_member: '{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical Comment representation","properties":{"object":{"type":"object","properties":{"text":{"type":"string"},"idea_id":{"type":"string"}},"required":[]}}}'

resourceTypes:
  - dolan_db_collection:
      usage: This resourceType should be used for any collection of items
      is: [ securedBySteroidsApiKey ]
      get:
        description: |
          {
            "action": "collection"
          }
        responses:
          200:
            description: |
              {
                "rootKey": "objects"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_collection # e.g cars
      post:
        description: |
          {
            "action": "create",
            "rootKey": "object"
          }
        body:
          application/json:
            schema: <<resourcePathName>>_member
        responses:
          200:
            description: |
              {
                "rootKey": "object"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_member # e.g. car

  - dolan_db_member:
      usage: This resourceType should be used for any built.io item
      is: [ securedBySteroidsApiKey ]
      get:
        description: |
          {
            "action": "find"
          }
        responses:
          200:
            description: |
              {
                "rootKey": "object"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_member # e.g. car
      put:
        description: |
          {
            "action": "update",
            "rootKey": "object"
          }
        body:
          application/json:
            schema: <<resourcePathName>>_member
        responses:
          200:
            description: |
              {
                "rootKey": "object"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_member
      delete:
        description: |
          {
            "action": "destroy"
          }
        responses:
          200:


/Idea:
  description: |
    {
      "resourceName": "Idea",
      "identifierKey": "id"
    }
  type: dolan_db_collection
  /{id}:
    type: dolan_db_member

/Comment:
  description: |
    {
      "resourceName": "Comment",
      "identifierKey": "id"
    }
  type: dolan_db_collection
  /{id}:
    type: dolan_db_member


